import { describe, expect, it } from "vitest";

import { AbstractException } from "../../driver/abstract-exception";
import { IdentityColumnsNotSupported } from "../../driver/exception/identity-columns-not-supported";
import { NoIdentityValue } from "../../driver/exception/no-identity-value";

class TestDriverException extends AbstractException {}

describe("Driver exception parity", () => {
  it("stores SQL state and code", () => {
    const cause = new Error("boom");
    const error = new TestDriverException("driver error", "08006", 123, cause);

    expect(error.message).toBe("driver error");
    expect(error.code).toBe(123);
    expect(error.getSQLState()).toBe("08006");
    expect((error as Error & { cause?: unknown }).cause).toBe(cause);
  });

  it("builds IdentityColumnsNotSupported factory exception", () => {
    const error = IdentityColumnsNotSupported.new();
    expect(error.message).toBe("The driver does not support identity columns.");
    expect(error.getSQLState()).toBeNull();
  });

  it("builds NoIdentityValue factory exception", () => {
    const error = NoIdentityValue.new();
    expect(error.message).toBe("No identity value was generated by the last statement.");
    expect(error.getSQLState()).toBeNull();
  });
});
