import { AbstractException } from "../abstract-exception";

export class NoIdentityValue extends AbstractException {
  public static new(cause?: unknown): NoIdentityValue {
    return new NoIdentityValue(
      "No identity value was generated by the last statement.",
      null,
      0,
      cause,
    );
  }
}
