import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { PostgreSQLPlatform } from "../../../platforms/postgresql-platform";
import { PostgreSQL120Platform } from "../../../platforms/postgresql120-platform";
import { Column } from "../../../schema/column";
import { Index } from "../../../schema/index";
import { IndexType } from "../../../schema/index/index-type";
import { PrimaryKeyConstraint } from "../../../schema/primary-key-constraint";
import { Table } from "../../../schema/table";
import { View } from "../../../schema/view";
import { DecimalType } from "../../../types/decimal-type";
import { IntegerType } from "../../../types/integer-type";
import { JsonType } from "../../../types/json-type";
import { TextType } from "../../../types/text-type";
import { Type } from "../../../types/type";
import { TypeRegistry } from "../../../types/type-registry";
import { Types } from "../../../types/types";
import { useFunctionalTestCase } from "../_helpers/functional-test-case";
import { MoneyType } from "./types/money-type";

describe("Functional/Schema/PostgreSQLSchemaManagerTest", () => {
  const functional = useFunctionalTestCase();
  const originalRegistry = Type.getTypeRegistry();

  beforeAll(() => {
    Type.setTypeRegistry(new TypeRegistry(originalRegistry.getMap()));
    if (!Type.hasType(MoneyType.NAME)) {
      Type.addType(MoneyType.NAME, new MoneyType());
    }
  });

  afterAll(() => {
    Type.setTypeRegistry(originalRegistry);
  });

  it("get schema names", async ({ skip }) => {
    if (!(functional.connection().getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    functional.assertUnqualifiedNameListContainsQuotedName(
      "public",
      await (await functional.connection().createSchemaManager()).introspectSchemaNames(),
    );
  });

  it("support domain type fallback", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    await connection.executeStatement("DROP TABLE IF EXISTS domain_type_test");
    await connection.executeStatement("DROP DOMAIN IF EXISTS mymoney");
    await connection.executeStatement("CREATE DOMAIN mymoney AS DECIMAL(18,2)");
    await connection.executeStatement(
      "CREATE TABLE domain_type_test (id INT PRIMARY KEY, value mymoney)",
    );

    const schemaManager = await connection.createSchemaManager();
    const decimalTable = await schemaManager.introspectTableByUnquotedName("domain_type_test");
    expect(decimalTable.getColumn("value").getType()).toBeInstanceOf(DecimalType);

    connection.getDatabasePlatform().registerDoctrineTypeMapping("mymoney", MoneyType.NAME);

    const customTypeTable = await schemaManager.introspectTableByUnquotedName("domain_type_test");
    expect(customTypeTable.getColumn("value").getType()).toBeInstanceOf(MoneyType);
  });

  it("alter table auto increment add", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    const schemaManager = await connection.createSchemaManager();

    const tableFrom = Table.editor()
      .setUnquotedName("autoinc_table_add")
      .setColumns(Column.editor().setUnquotedName("id").setTypeName(Types.INTEGER).create())
      .create();

    await functional.dropAndCreateTable(tableFrom);
    const tableFromOnline = await schemaManager.introspectTableByUnquotedName("autoinc_table_add");
    expect(tableFromOnline.getColumn("id").getAutoincrement()).toBe(false);

    const tableTo = Table.editor()
      .setUnquotedName("autoinc_table_add")
      .setColumns(
        Column.editor()
          .setUnquotedName("id")
          .setTypeName(Types.INTEGER)
          .setAutoincrement(true)
          .create(),
      )
      .create();

    const diff = schemaManager.createComparator().compareTables(tableFromOnline, tableTo);

    expect(diff).not.toBeNull();
    if (diff === null) {
      return;
    }

    expect(connection.getDatabasePlatform().getAlterTableSQL(diff)).toEqual([
      "ALTER TABLE autoinc_table_add ALTER id ADD GENERATED BY DEFAULT AS IDENTITY",
    ]);

    await schemaManager.alterTable(diff);
    const tableFinal = await schemaManager.introspectTableByUnquotedName("autoinc_table_add");
    expect(tableFinal.getColumn("id").getAutoincrement()).toBe(true);
  });

  it("alter table auto increment drop", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    const schemaManager = await connection.createSchemaManager();

    const tableFrom = Table.editor()
      .setUnquotedName("autoinc_table_drop")
      .setColumns(
        Column.editor()
          .setUnquotedName("id")
          .setTypeName(Types.INTEGER)
          .setAutoincrement(true)
          .create(),
      )
      .create();

    await functional.dropAndCreateTable(tableFrom);
    const tableFromOnline = await schemaManager.introspectTableByUnquotedName("autoinc_table_drop");
    expect(tableFromOnline.getColumn("id").getAutoincrement()).toBe(true);

    const tableTo = Table.editor()
      .setUnquotedName("autoinc_table_drop")
      .setColumns(Column.editor().setUnquotedName("id").setTypeName(Types.INTEGER).create())
      .create();

    const diff = schemaManager.createComparator().compareTables(tableFromOnline, tableTo);

    expect(diff).not.toBeNull();
    if (diff === null) {
      return;
    }

    expect(connection.getDatabasePlatform().getAlterTableSQL(diff)).toEqual([
      "ALTER TABLE autoinc_table_drop ALTER id DROP IDENTITY",
    ]);

    await schemaManager.alterTable(diff);
    const tableFinal = await schemaManager.introspectTableByUnquotedName("autoinc_table_drop");
    expect(tableFinal.getColumn("id").getAutoincrement()).toBe(false);
  });

  it("list same table name columns with different schema", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    await connection.executeStatement("DROP SCHEMA IF EXISTS another CASCADE");
    await connection.executeStatement("CREATE SCHEMA IF NOT EXISTS another");
    await connection.executeStatement('DROP TABLE IF EXISTS "table"');
    await connection.executeStatement('DROP TABLE IF EXISTS another."table"');

    const schemaManager = await connection.createSchemaManager();
    await connection.executeStatement("DROP VIEW IF EXISTS list_tables_excludes_views_test_view");

    const table = Table.editor()
      .setUnquotedName("table")
      .setColumns(
        Column.editor().setUnquotedName("id").setTypeName(Types.INTEGER).create(),
        Column.editor().setUnquotedName("name").setTypeName(Types.TEXT).create(),
      )
      .create();

    const anotherSchemaTable = Table.editor()
      .setUnquotedName("table", "another")
      .setColumns(
        Column.editor().setUnquotedName("id").setTypeName(Types.TEXT).create(),
        Column.editor().setUnquotedName("email").setTypeName(Types.TEXT).create(),
      )
      .create();

    await schemaManager.createTable(table);
    await schemaManager.createTable(anotherSchemaTable);

    const tableInPublicSchema = await schemaManager.introspectTableByUnquotedName("table");
    expect(tableInPublicSchema.getColumns()).toHaveLength(2);
    expect(tableInPublicSchema.hasColumn("id")).toBe(true);
    expect(tableInPublicSchema.getColumn("id").getType()).toBeInstanceOf(IntegerType);
    expect(tableInPublicSchema.hasColumn("name")).toBe(true);

    const tableInAnotherSchema = await schemaManager.introspectTableByUnquotedName(
      "table",
      "another",
    );
    expect(tableInAnotherSchema.getColumns()).toHaveLength(2);
    expect(tableInAnotherSchema.hasColumn("id")).toBe(true);
    expect(tableInAnotherSchema.getColumn("id").getType()).toBeInstanceOf(TextType);
    expect(tableInAnotherSchema.hasColumn("email")).toBe(true);
  });

  it("return quoted assets", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    await connection.executeStatement("DROP TABLE IF EXISTS dbal91_something");
    await connection.executeStatement(
      'create table dbal91_something (id integer CONSTRAINT id_something PRIMARY KEY NOT NULL, "table" integer)',
    );
    await connection.executeStatement(
      'ALTER TABLE dbal91_something ADD CONSTRAINT something_input FOREIGN KEY( "table" ) REFERENCES dbal91_something ON UPDATE CASCADE;',
    );

    const schemaManager = await connection.createSchemaManager();
    const table = await schemaManager.introspectTable("dbal91_something");

    expect(connection.getDatabasePlatform().getCreateTableSQL(table)).toEqual([
      'CREATE TABLE dbal91_something (id INT NOT NULL, "table" INT DEFAULT NULL, PRIMARY KEY (id))',
      'CREATE INDEX IDX_A9401304ECA7352B ON dbal91_something ("table")',
      'ALTER TABLE dbal91_something ADD CONSTRAINT something_input FOREIGN KEY ("table") REFERENCES dbal91_something (id) ON UPDATE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE',
    ]);
  });

  it("default value character varying", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    const table = Table.editor()
      .setUnquotedName("dbal511_default")
      .setColumns(
        Column.editor().setUnquotedName("id").setTypeName(Types.INTEGER).create(),
        Column.editor()
          .setUnquotedName("def")
          .setTypeName(Types.STRING)
          .setDefaultValue("foo")
          .create(),
      )
      .setPrimaryKeyConstraint(PrimaryKeyConstraint.editor().setUnquotedColumnNames("id").create())
      .create();

    await functional.dropAndCreateTable(table);

    const databaseTable = await (await connection.createSchemaManager()).introspectTable(
      table.getObjectName().toString(),
    );
    expect(databaseTable.getColumn("def").getDefault()).toBe("foo");
  });

  it("json default value", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    const table = Table.editor()
      .setUnquotedName("test_json")
      .setColumns(
        Column.editor()
          .setUnquotedName("foo")
          .setTypeName(Types.JSON)
          .setDefaultValue('{"key": "value with a single quote \' in string value"}')
          .create(),
      )
      .create();

    await functional.dropAndCreateTable(table);

    const [column] = await (
      await connection.createSchemaManager()
    ).introspectTableColumnsByUnquotedName("test_json");

    expect(column).toBeDefined();
    if (column === undefined) {
      return;
    }

    expect(column.getType()).toBe(Type.getType(Types.JSON));
    expect(column.getDefault()).toBe('{"key": "value with a single quote \' in string value"}');
  });

  it("boolean default", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    const table = Table.editor()
      .setUnquotedName("ddc2843_bools")
      .setColumns(
        Column.editor().setUnquotedName("id").setTypeName(Types.INTEGER).create(),
        Column.editor()
          .setUnquotedName("checked")
          .setTypeName(Types.BOOLEAN)
          .setDefaultValue(false)
          .create(),
      )
      .create();

    await functional.dropAndCreateTable(table);

    const schemaManager = await connection.createSchemaManager();
    const databaseTable = await schemaManager.introspectTable(table.getObjectName().toString());
    const diff = schemaManager.createComparator().compareTables(table, databaseTable);

    expect(diff === null || diff.isEmpty()).toBe(true);
  });

  it("list tables excludes views", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    const schemaManager = await connection.createSchemaManager();

    const table = Table.editor()
      .setUnquotedName("list_tables_excludes_views")
      .setColumns(Column.editor().setUnquotedName("id").setTypeName(Types.INTEGER).create())
      .create();

    await functional.dropAndCreateTable(table);

    const view = View.editor()
      .setUnquotedName("list_tables_excludes_views_test_view")
      .setSQL("SELECT * from list_tables_excludes_views")
      .create();
    await schemaManager.createView(view);

    const tables = await schemaManager.listTables();
    const foundView = tables.find(
      (candidate) => candidate.getName().toLowerCase() === "list_tables_excludes_views_test_view",
    );

    expect(foundView).toBeUndefined();
  });

  it("partial indexes", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    const table = Table.editor()
      .setUnquotedName("person")
      .setColumns(
        Column.editor().setUnquotedName("id").setTypeName(Types.INTEGER).create(),
        Column.editor().setUnquotedName("name").setTypeName(Types.STRING).create(),
        Column.editor().setUnquotedName("email").setTypeName(Types.STRING).create(),
      )
      .setIndexes(
        Index.editor()
          .setUnquotedName("simple_partial_index")
          .setType(IndexType.UNIQUE)
          .setUnquotedColumnNames("id", "name")
          .setPredicate("(id IS NULL)")
          .create(),
      )
      .create();

    await functional.dropAndCreateTable(table);

    const schemaManager = await connection.createSchemaManager();
    const onlineTable = await schemaManager.introspectTableByUnquotedName("person");

    const diff = schemaManager.createComparator().compareTables(table, onlineTable);
    expect(diff === null || diff.isEmpty()).toBe(true);
    expect(onlineTable.hasIndex("simple_partial_index")).toBe(true);

    const index = onlineTable.getIndex("simple_partial_index");
    expect(index.hasOption("where")).toBe(true);
    expect(index.getOption("where")).toBe("(id IS NULL)");
  });

  it("jsonb column", async ({ skip }) => {
    const connection = functional.connection();
    if (!(connection.getDatabasePlatform() instanceof PostgreSQLPlatform)) {
      skip();
    }

    const column = Column.editor().setUnquotedName("foo").setTypeName(Types.JSON).create();
    column.setPlatformOption("jsonb", true);

    const table = Table.editor().setUnquotedName("test_jsonb").setColumns(column).create();
    await functional.dropAndCreateTable(table);

    const columns = await (await connection.createSchemaManager()).listTableColumns("test_jsonb");
    const foo = columns.find((item) => item.getName().toLowerCase() === "foo");

    expect(foo).toBeDefined();
    if (foo === undefined) {
      return;
    }

    expect(foo.getType()).toBeInstanceOf(JsonType);
    expect(foo.getPlatformOption("jsonb")).toBe(true);
  });

  it("generated column", async ({ skip }) => {
    const connection = functional.connection();
    const platform = connection.getDatabasePlatform();
    if (!(platform instanceof PostgreSQLPlatform)) {
      skip();
    }

    if (!(platform instanceof PostgreSQL120Platform)) {
      skip();
    }

    const table = Table.editor()
      .setUnquotedName("ddc6198_generated_always_as")
      .setColumns(
        Column.editor().setUnquotedName("id").setTypeName(Types.INTEGER).create(),
        Column.editor()
          .setUnquotedName("idIsOdd")
          .setTypeName(Types.BOOLEAN)
          .setColumnDefinition("boolean GENERATED ALWAYS AS (id % 2 = 1) STORED")
          .setNotNull(false)
          .create(),
      )
      .create();

    await functional.dropAndCreateTable(table);

    const schemaManager = await connection.createSchemaManager();
    const databaseTable = await schemaManager.introspectTable(table.getObjectName().toString());
    const diff = schemaManager.createComparator().compareTables(table, databaseTable);

    expect(diff === null || diff.isEmpty()).toBe(true);
  });
});
