name: Tests

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ngandu-dev/.github/.github/workflows/node-test.yml@main
